name: Deploy

on:
  push:
    branches:
      - master

env:
  SERVER_HOST: andranik1.beget.tech
  SERVER_USER: andranik1
  SERVER_PORT: 22
  SERVER_PASS: RwhdMjHU
  SERVER_PATH: /home/a/andranik1/akonsalt-finance.ru/public_html

  TG_BOT_TOKEN: "7208914864:AAE03jASMF8B0C-P8NWokK__ZH722u6B0gk"
  TG_ID_CHANEL: "-1002204160156"

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install npm dependencies
        run: npm install

      - name: Run build
        run: npm run build

      - name: Deploy to Server
        id: deploy_step
        uses: easingthemes/ssh-deploy@main
        with:
          # ssh-keygen -m PEM -t rsa -b 4096
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
          ARGS: "-rlgoDzvc -i --delete --exclude='.htaccess'"
          SOURCE: "dist/"
          REMOTE_HOST: ${{ env.SERVER_HOST }}
          REMOTE_PORT: ${{ env.SERVER_PORT }}
          REMOTE_USER: ${{ env.SERVER_USER }}
          TARGET: ${{ env.SERVER_PATH }}
          EXCLUDE: "/dist/, /node_modules/, /.github/"
        continue-on-error: true

      - name: Success Deploy
        if: steps.deploy_step.outcome == 'success'
        uses: appleboy/telegram-action@master
        with:
          to: ${{ env.TG_ID_CHANEL }}
          token: ${{ env.TG_BOT_TOKEN }}
          message: |
            ‚úÖ Deploy CI/CD —É—Å–ø–µ—à–Ω–æ –≤—ã–ø–æ–ª–Ω–µ–Ω!

            üìÇ –†–µ–ø–æ–∑–∏—Ç–æ—Ä–∏–π: https://github.com/${{ github.repository }}
            üë§ "${{ github.actor }}" —Å–¥–µ–ª–∞–ª –∫–æ–º–º–∏—Ç:
            üìù ${{ github.event.commits[0].message }}

            –ü–æ—Å–º–æ—Ç—Ä–µ—Ç—å –∏–∑–º–µ–Ω–µ–Ω–∏—è: https://github.com/${{ github.repository }}/commit/${{ github.sha }}

      - name: Success Deploy
        if: steps.deploy_step.outcome != 'success'
        uses: appleboy/telegram-action@master
        with:
          to: ${{ env.TG_ID_CHANEL }}
          token: ${{ env.TG_BOT_TOKEN }}
          message: |
            ‚ùå Action CI/CD –∑–∞–≤–µ—Ä—à–∏–ª—Å—è —Å –æ—à–∏–±–∫–æ–π :(
            
            –ü—Ä–æ–≤–µ—Ä—å—Ç–µ –ª–æ–≥–∏ –¥–ª—è –ø–æ–ª—É—á–µ–Ω–∏—è –ø–æ–¥—Ä–æ–±–Ω–æ—Å—Ç–µ–π.
            
            üìÇ –†–µ–ø–æ–∑–∏—Ç–æ—Ä–∏–π: https://github.com/${{ github.repository }}
            üë§ "${{ github.actor }}" —Å–¥–µ–ª–∞–ª –∫–æ–º–º–∏—Ç:
            üìù ${{ github.event.commits[0].message }}
            
            –ü–æ—Å–º–æ—Ç—Ä–µ—Ç—å –∏–∑–º–µ–Ω–µ–Ω–∏—è: https://github.com/${{ github.repository }}/commit/${{ github.sha }}